export const LABELS: Record<string, readonly [string, string]> = {
  preparatory: ["Preparatory", "إعدادي"],
  secondary: ["Secondary", "ثانوي"],
  prep_1: ["First Preparatory", "أولى إعدادي"],
  prep_2: ["Second Preparatory", "تانية إعدادي"],
  prep_3: ["Third Preparatory", "تالتة إعدادي"],
  secondary_1: ["First Secondary", "أولى ثانوي"],
  secondary_2: ["Second Secondary", "تانية ثانوي"],
  secondary_3: ["Third Secondary", "تالتة ثانوي"],
  general_secondary: ["General Secondary", "الثانوية العامة"],
  egyptian_baccalaureate: ["Egyptian Baccalaureate", "البكالوريا المصرية"],
  scientific: ["Scientific", "علمي"],
  literary: ["Literary", "أدبي"],
  science: ["Science", "علمي علوم"],
  mathematics: ["Mathematics", "الرياضيات"],
  medicine_life_sciences: ["Medicine & Life Sciences", "الطب وعلوم الحياة"],
  engineering_computer_science: [
    "Engineering & Computer Science",
    "الهندسة وعلوم الحاسب",
  ],
  business: ["Business", "الأعمال"],
  arts_humanities: ["Arts & Humanities", "الآداب والفنون"],
  arabic: ["Arabic", "اللغة العربية"],
  first_language: ["First Foreign Language", "اللغة الأجنبية الأولى"],
  history: ["History", "التاريخ"],
  integrated_science: ["Integrated Science", "العلوم المتكاملة"],
  philosophy_logic: ["Philosophy & Logic", "الفلسفة والمنطق"],
  religion: ["Religious Education", "التربية الدينية"],
  second_language: ["Second Foreign Language", "اللغة الأجنبية الثانية"],
  physical_education: ["Physical Education", "التربية الرياضية"],
  programming_ai: ["Programming & AI", "البرمجة والذكاء الاصطناعي"],
  physics: ["Physics", "الفيزياء"],
  chemistry: ["Chemistry", "الكيمياء"],
  geography: ["Geography", "الجغرافيا"],
  psychology: ["Psychology", "علم النفس"],
  biology: ["Biology", "الأحياء"],
  statistics: ["Statistics", "الإحصاء"],
  national_education: ["National Education", "التربية الوطنية"],
  accounting: ["Accounting", "المحاسبة"],
  business_administration: ["Business Administration", "إدارة الأعمال"],
  financial_literacy: ["Financial Literacy", "الثقافة المالية"],
  advanced_biology: ["Advanced Biology", "الأحياء — مستوى متقدم"],
  advanced_chemistry: ["Advanced Chemistry", "الكيمياء — مستوى متقدم"],
  advanced_mathematics: ["Advanced Mathematics", "الرياضيات — مستوى متقدم"],
  advanced_physics: ["Advanced Physics", "الفيزياء — مستوى متقدم"],
  advanced_economics: ["Advanced Economics", "الاقتصاد — مستوى متقدم"],
  advanced_geography: ["Advanced Geography", "الجغرافيا — مستوى متقدم"],
  science_subject: ["Science", "العلوم"],
  social_studies: ["Social Studies", "الدراسات الاجتماعية"],
};
